language: perl
perl:
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "cpanm Dist::Zilla"
  - "cpanm Dist::Zilla::PluginBundle::Author::MELO"
  - "git config --global github.user melo"
install: "dzil authordeps | xargs cpanm && dzil listdeps | xargs cpanm"
script: "dzil test --release"
